---
abstract: 'Package for connect WebInterface with PSGI'
author:
  - 'Igor Sverdlov <igor-sverdlov@mail.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: QBit-WebInterface-PSGI
requires:
  QBit::WebInterface: '0'
  QBit::WebInterface::Request: '0'
  URI::Escape: '0'
  base: '0'
  qbit: '0'
version: '0.004'
x_serialization_backend: 'YAML::Tiny version 1.70'
